# Generated by Django 6.0.2 on 2026-02-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان السؤال')),
                ('content', models.TextField(verbose_name='محتوى السؤال')),
                ('subject', models.CharField(choices=[('arabic', 'اللغة العربية'), ('math', 'الرياضيات'), ('science', 'العلوم'), ('social', 'الدراسات الاجتماعية'), ('english', 'اللغة الإنجليزية'), ('islamic', 'التربية الإسلامية'), ('other', 'أخرى')], default='arabic', max_length=50, verbose_name='المادة')),
                ('grade', models.CharField(choices=[('1', 'الصف 1'), ('2', 'الصف 2'), ('3', 'الصف 3'), ('4', 'الصف 4'), ('5', 'الصف 5'), ('6', 'الصف 6')], default='1', max_length=2, verbose_name='الصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['-created_at'],
            },
        ),
    ]
